apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-rheljdk11-sample
  labels:
    app: tomcat-rheljdk11-sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat-rheljdk11-sample
  template:
    metadata:
      labels:
        app: tomcat-rheljdk11-sample
    spec:
      containers:
        - name: tomcat-rheljdk11-sample
          image: "default-route-openshift-image-registry.apps.sandbox-m2.ll9k.p1.openshiftapps.com/karthick5268a-dev/tomcat-rheljdk11:9.0.71"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: serve
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-rheljdk11-sample-svc
  labels:
    app: tomcat-rheljdk11-sample-svc
spec:
  type: ClusterIP
  ports:
  - name: tomcat-rheljdk11-sample
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: tomcat-rheljdk11-sample
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: tomcat-rheljdk11-sample-route
  labels:
    app: tomcat-rheljdk11-sample-svc
spec:
  # hostname: foo.apps.CLUSTER.ccs.ornl.gov
  port:
    targetPort: tomcat-rheljdk11-sample
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: tomcat-rheljdk11-sample-svc
    weight: 100
  wildcardPolicy: None